Feature/microservice properties file
idrsolutions/formvu-microservice-example pull request #16
Opened 2021-12-21 09:22 UTC by KieranFrance

Config file is finished as is and ready to add to develop for use in other tasks

2021-12-23 16:08 UTC, JacobIDR requested changes

2021-12-23 16:08 UTC, JacobIDR commented on src/main/java/com/idrsolutions/microservice/FormVuServletContextListener.java
> +    public void validateConfigFileValues(final Properties propertiesFile) {
Does this need to be implemented if it's just calling the super?
Also should it be changing the access modifier? (protected -> public)

2022-01-04 12:15 UTC, JacobIDR approved these changes

2022-01-13 16:04 UTC, daniel-warren approved these changes

2022-01-18 14:16 UTC, merged