Implement RMI in FormVu microservice
idrsolutions/formvu-microservice-example pull request #42
Opened 2023-11-22 14:49 UTC by daniel-warren

Implements the changes from https://github.com/idrsolutions/base-microservice-example/pull/72 into the FormVu microservice

2023-11-23 18:07 UTC, leonatherton requested changes
Made a couple of suggestions. Will need the merge conflict resolved also.

2023-11-23 18:07 UTC, leonatherton commented on pom.xml
> +            <version>11.0.1</version>
```suggestion
            <version>12.0.1</version>
```

2023-11-23 18:07 UTC, leonatherton commented on src/main/java/com/idrsolutions/microservice/FormVuServlet.java
> +                webappDirectory = "WEB-INF/lib/formvu.jar:.";
```suggestion
                webappDirectory = "WEB-INF/lib/formvu.jar" + File.pathSeparatorChar + '.';
```

2023-11-28 13:12 UTC, KieranFrance approved these changes

2023-11-29 09:19 UTC, Amy1612 approved these changes

2023-11-29 09:28 UTC, merged